### ISSUE TITLE
Modifiers not transferring from DnD Beyond to Discord

### ISSUE THREAD

**Issue by michaeldescado** [nick-vanpraet/dndbeyonddigitaldicefordiscord#4]
<img width="660" alt="preroll" src="https://user-images.githubusercontent.com/75173135/100519090-fb696600-3152-11eb-943d-fe308018a458.png">
<img width="672" alt="roll" src="https://user-images.githubusercontent.com/75173135/100519093-002e1a00-3153-11eb-9901-6e9c6ac5888d.png">
<img width="694" alt="calculation" src="https://user-images.githubusercontent.com/75173135/100519095-045a3780-3153-11eb-8941-46021e12512d.png">
<img width="682" alt="roll xfered to discord" src="https://user-images.githubusercontent.com/75173135/100519098-08865500-3153-11eb-9f18-f2e272e12ec5.png">

**Comment by michaeldescado** [comment]
So the pics pretty much tell the story, but I wanted to write just a little.  First, thank you for this extension.  It's really helpful!  The issue I'm having is that the modifiers on dice rolls that are present on the D&D Beyond side, are not transferring over to Discord.  Instead, just the raw die roll appears without any modifiers.  Am I doing something wrong?  Just let me know.
Thanks!
-Mike

**Comment by nick-vanpraet** [comment]
For some reason, Beyond20 is changing the dice result popup which is what this extension reads. Try disabling Beyond20 and rolling again, it should then send the modifier and all data to Discord properly.

**Comment by michaeldescado** [comment]
Thank you!  This was very helpful.  :)
    On Saturday, November 28, 2020, 11:40:03 AM MST, nick-vanpraet <notifications@github.com> wrote:  
 
 


For some reason, Beyond20 is changing the dice result popup which is what this extension reads. Try disabling Beyond20 and rolling again, it should then send the modifier and all data to Discord properly.
